### ISSUE TITLE
Bug d'exemple

### ISSUE THREAD

**Issue by 7lele** [AigloOo/BalDev#4]
Lorsque j'appuie sur une `propriété` je vois le **Nom**, la **Définition**, et l'**Explication de l'éxemple** mais l'`Exemple` est _manquant_

Images : 

![Capture-2024-02-16-191941](https://github.com/AigloOo/BalDev/assets/118902819/ed0e93b7-90c3-47d7-a55b-1e765bfd85bf)

![Documentation HTML - BalDev](https://github.com/AigloOo/BalDev/assets/118902819/a1a84262-345f-4975-855e-4fe57411c545)

**Comment by AigloOo** [comment]
Bonsoir, tu n'as pas pris le bon exemple car celui-ci n'est pas très visible. En effet, c'est une idée et on ne peut pas vraiment la montrer visuellement car cela n'a pas d'impact sur le visuel. Merci quand même de ton investissement.

**Comment by AigloOo** [comment]
Tu m'as fait penser à rajouter un texte qui indique qu'il ne peut pas y avoir d'exemple.
